services:
  puyuan:
    image: python:3.12-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    tty: true
