# Generated by Django 5.1 on 2024-08-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
