# Generated by Django 5.1 on 2024-08-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userauth_created_at_alter_userauth_login_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='fb_id',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='fcm_id',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='login_times',
        ),
    ]
