# Generated by Django 5.1 on 2024-08-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userauth_fb_id_remove_userauth_fcm_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='privacy_polocy',
            new_name='privacy_policy',
        ),
    ]
