# Generated by Django 5.1 on 2024-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_privacy_polocy_userauth_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
