# Generated by Django 5.1 on 2024-08-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userauth_code_alter_userauth_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
