# Generated by Django 5.1.1 on 2024-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userauth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='phone',
            field=models.CharField(blank=True, default='null', max_length=50, null=True, unique=True),
        ),
    ]
