# Generated by Django 5.1.1 on 2024-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='read',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
