# Generated by Django 5.1.1 on 2024-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sugar_delta_max', models.IntegerField(null=True)),
                ('sugar_delta_min', models.IntegerField(null=True)),
                ('sugar_morning_max', models.IntegerField(null=True)),
                ('sugar_morning_min', models.IntegerField(null=True)),
                ('sugar_evening_max', models.IntegerField(null=True)),
                ('sugar_evening_min', models.IntegerField(null=True)),
                ('sugar_before_max', models.IntegerField(null=True)),
                ('sugar_before_min', models.IntegerField(null=True)),
                ('sugar_after_max', models.IntegerField(null=True)),
                ('sugar_after_min', models.IntegerField(null=True)),
                ('systolic_max', models.IntegerField(null=True)),
                ('systolic_min', models.IntegerField(null=True)),
                ('diastolic_max', models.IntegerField(null=True)),
                ('diastolic_min', models.IntegerField(null=True)),
                ('pulse_max', models.IntegerField(null=True)),
                ('pulse_min', models.IntegerField(null=True)),
                ('weight_max', models.IntegerField(null=True)),
                ('weight_min', models.IntegerField(null=True)),
                ('bmi_max', models.IntegerField(null=True)),
                ('bmi_min', models.IntegerField(null=True)),
                ('body_fat_max', models.IntegerField(null=True)),
                ('body_fat_min', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
