# Generated by Django 5.1.1 on 2024-09-16 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userauth_email'),
        ('user', '0004_alter_default_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('after_recording', models.BooleanField(null=True)),
                ('no_recording_for_a_day', models.BooleanField(null=True)),
                ('over_max_or_under_min', models.BooleanField(null=True)),
                ('after_meal', models.BooleanField(null=True)),
                ('unit_of_sugar', models.BooleanField(null=True)),
                ('unit_of_weight', models.BooleanField(null=True)),
                ('unit_of_height', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
