# Generated by Django 5.1.1 on 2024-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_bloodpressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.FloatField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='pulse',
            field=models.FloatField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.FloatField(max_length=3, null=True),
        ),
    ]
