# Generated by Django 5.1.1 on 2024-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bloodpressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='recorded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
