# Generated by Django 5.1.1 on 2024-09-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userauth_email'),
        ('user', '0008_alter_bloodpressure_recorded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugar',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sugar', models.IntegerField(null=True)),
                ('timeperiod', models.IntegerField(null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.FloatField(max_length=3, null=True)),
                ('body_fat', models.FloatField(max_length=3, null=True)),
                ('bmi', models.FloatField(max_length=3, null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
