# Generated by Django 5.1.1 on 2024-09-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userauth_email'),
        ('user', '0009_bloodsugar_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryDiet',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.IntegerField(max_length=100, null=True)),
                ('meal', models.IntegerField(null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('image', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
