# Generated by Django 5.1.1 on 2024-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_diarydiet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarydiet',
            name='description',
            field=models.IntegerField(null=True),
        ),
    ]
