# Generated by Django 5.1.1 on 2024-09-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_bloodpressure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
