# Generated by Django 5.1.1 on 2024-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_hba1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hba1c',
            name='a1c',
            field=models.IntegerField(null=True),
        ),
    ]
