# Generated by Django 5.1.1 on 2024-09-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userauth_email'),
        ('user', '0022_druginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCare',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('member_id', models.IntegerField(null=True)),
                ('reply_id', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
