# Generated by Django 5.1.1 on 2024-09-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_usercare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCare',
        ),
    ]
