# Generated by Django 5.1.1 on 2024-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_default_bmi_max_alter_default_bmi_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
