# Generated by Django 5.1.1 on 2024-09-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_default_bmi_min_alter_default_body_fat_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='bmi_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
