# Generated by Django 5.1.1 on 2024-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_default_bmi_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='bmi_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='bmi_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='body_fat_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='body_fat_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='diastolic_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='diastolic_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='pulse_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='pulse_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_after_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_after_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_before_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_before_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_delta_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_delta_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_evening_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_evening_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_morning_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='sugar_morning_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='systolic_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='systolic_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='weight_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='default',
            name='weight_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inviteCode',
            field=models.CharField(default='null', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
