# Generated by Django 5.1.1 on 2024-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_medicalinfo_anti_hypertensives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
