# Generated by Django 5.1.1 on 2024-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercare',
            name='member_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usercare',
            name='reply_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
